insert into restoraunts (name, location) values ('Cchaddie', 'Room 943');
insert into restoraunts (name, location) values ('Murvyn', '16th Floor');
insert into restoraunts (name, location) values ('Dill', 'PO Box 12888');
insert into restoraunts (name, location) values ('Elliot', 'Suite 24');
insert into restoraunts (name, location) values ('Jarib', 'PO Box 83837');
insert into restoraunts (name, location) values ('Elmo', 'Suite 98');
insert into restoraunts (name, location) values ('Ranique', '14th Floor');
insert into restoraunts (name, location) values ('Vale', 'Apt 1445');
insert into restoraunts (name, location) values ('Rudiger', 'PO Box 64991');
insert into restoraunts (name, location) values ('Cybil', 'Room 1345');
insert into restoraunts (name, location) values ('Audre', '14th Floor');
insert into restoraunts (name, location) values ('Giovanna', 'Apt 1211');
insert into restoraunts (name, location) values ('Anissa', '5th Floor');
insert into restoraunts (name, location) values ('Bibby', 'Room 1524');
insert into restoraunts (name, location) values ('Mordy', 'PO Box 51537');
insert into restoraunts (name, location) values ('Flore', 'PO Box 47723');
insert into restoraunts (name, location) values ('Grannie', 'Suite 10');
insert into restoraunts (name, location) values ('Ivory', 'Apt 1187');
insert into restoraunts (name, location) values ('Mira', 'Apt 1760');
insert into restoraunts (name, location) values ('Perkin', 'PO Box 39128');
insert into restoraunts (name, location) values ('Gerhardt', '10th Floor');
insert into restoraunts (name, location) values ('Bethina', '4th Floor');
insert into restoraunts (name, location) values ('Madelaine', 'Room 1449');
insert into restoraunts (name, location) values ('Sarajane', 'Suite 41');
insert into restoraunts (name, location) values ('Sandy', '6th Floor');
insert into restoraunts (name, location) values ('Cara', 'Suite 93');
insert into restoraunts (name, location) values ('Dulcine', 'Apt 230');
insert into restoraunts (name, location) values ('Vasili', '9th Floor');
insert into restoraunts (name, location) values ('Jorey', '6th Floor');
insert into restoraunts (name, location) values ('Davita', 'Suite 74');
insert into restoraunts (name, location) values ('Emile', 'Room 1565');
insert into restoraunts (name, location) values ('Weidar', 'Room 631');
insert into restoraunts (name, location) values ('Demetrius', 'Room 1669');
insert into restoraunts (name, location) values ('Zola', 'Room 496');
insert into restoraunts (name, location) values ('Frederica', 'Room 1183');
insert into restoraunts (name, location) values ('Bart', '11th Floor');
insert into restoraunts (name, location) values ('Robbin', 'PO Box 33349');
insert into restoraunts (name, location) values ('Marnia', 'Suite 5');
insert into restoraunts (name, location) values ('Byran', 'Suite 92');
insert into restoraunts (name, location) values ('Alexis', 'Apt 205');
insert into restoraunts (name, location) values ('Christy', '11th Floor');
insert into restoraunts (name, location) values ('Edin', 'PO Box 66895');
insert into restoraunts (name, location) values ('Gamaliel', 'Suite 7');
insert into restoraunts (name, location) values ('Matty', 'PO Box 3599');
insert into restoraunts (name, location) values ('Christen', '19th Floor');
insert into restoraunts (name, location) values ('Ferrel', 'Suite 72');
insert into restoraunts (name, location) values ('Antin', '9th Floor');
insert into restoraunts (name, location) values ('Margot', 'Suite 83');
insert into restoraunts (name, location) values ('Jamey', '5th Floor');
insert into restoraunts (name, location) values ('Mandi', 'Apt 507');
insert into restoraunts (name, location) values ('Skippie', '10th Floor');
insert into restoraunts (name, location) values ('Valina', 'Apt 1212');
insert into restoraunts (name, location) values ('Beatriz', 'Room 1088');
insert into restoraunts (name, location) values ('Roselia', 'PO Box 34322');
insert into restoraunts (name, location) values ('Yul', 'Suite 1');
insert into restoraunts (name, location) values ('Cathe', 'Room 417');
insert into restoraunts (name, location) values ('Carri', '16th Floor');
insert into restoraunts (name, location) values ('Bernie', 'Apt 11');
insert into restoraunts (name, location) values ('Nellie', 'Suite 73');
insert into restoraunts (name, location) values ('Yorker', 'Room 1818');
insert into restoraunts (name, location) values ('Gibbie', '15th Floor');
insert into restoraunts (name, location) values ('Jannelle', '18th Floor');
insert into restoraunts (name, location) values ('Neils', 'Suite 39');
insert into restoraunts (name, location) values ('Miguela', 'PO Box 83649');
insert into restoraunts (name, location) values ('Glenda', 'Suite 36');
insert into restoraunts (name, location) values ('Aeriel', 'PO Box 41548');
insert into restoraunts (name, location) values ('Jedidiah', 'Apt 1464');
insert into restoraunts (name, location) values ('Karalynn', 'Room 1982');
insert into restoraunts (name, location) values ('Alley', 'Suite 63');
insert into restoraunts (name, location) values ('Beverie', 'Suite 21');
insert into restoraunts (name, location) values ('Emerson', '3rd Floor');
insert into restoraunts (name, location) values ('Hatty', 'Suite 80');
insert into restoraunts (name, location) values ('Nicoli', 'Room 1082');
insert into restoraunts (name, location) values ('Martino', 'Apt 1903');
insert into restoraunts (name, location) values ('Lari', 'Room 526');
insert into restoraunts (name, location) values ('Valentino', 'PO Box 12925');
insert into restoraunts (name, location) values ('Lauren', '5th Floor');
insert into restoraunts (name, location) values ('Jerome', 'PO Box 46529');
insert into restoraunts (name, location) values ('Eryn', 'PO Box 867');
insert into restoraunts (name, location) values ('Trenna', 'Apt 609');
insert into restoraunts (name, location) values ('Giraud', 'Apt 1450');
insert into restoraunts (name, location) values ('Raphael', 'Room 1494');
insert into restoraunts (name, location) values ('Harrie', 'Room 268');
insert into restoraunts (name, location) values ('Adelaide', 'Apt 576');
insert into restoraunts (name, location) values ('Sayers', 'Room 212');
insert into restoraunts (name, location) values ('Brigitte', 'PO Box 8448');
insert into restoraunts (name, location) values ('Millicent', '3rd Floor');
insert into restoraunts (name, location) values ('Arlen', '5th Floor');
insert into restoraunts (name, location) values ('Gaspard', 'Apt 1358');
insert into restoraunts (name, location) values ('Neil', '17th Floor');
insert into restoraunts (name, location) values ('Brandy', 'Room 1060');
insert into restoraunts (name, location) values ('Pepillo', 'Suite 3');
insert into restoraunts (name, location) values ('Ewell', 'Room 813');
insert into restoraunts (name, location) values ('Ki', 'Suite 39');
insert into restoraunts (name, location) values ('Edi', 'Apt 192');
insert into restoraunts (name, location) values ('Estevan', 'Suite 85');
insert into restoraunts (name, location) values ('Silas', '9th Floor');
insert into restoraunts (name, location) values ('Jacquenette', 'Apt 1357');
insert into restoraunts (name, location) values ('Corry', 'PO Box 77317');
insert into restoraunts (name, location) values ('Darline', 'PO Box 46274');
insert into restoraunts (name, location) values ('Nicola', '4th Floor');
insert into restoraunts (name, location) values ('Noemi', 'Room 514');
insert into restoraunts (name, location) values ('Mitchel', 'Apt 541');
insert into restoraunts (name, location) values ('Alanna', 'Suite 90');
insert into restoraunts (name, location) values ('Doro', 'Room 1587');
insert into restoraunts (name, location) values ('Guinna', '11th Floor');
insert into restoraunts (name, location) values ('Melessa', '14th Floor');
insert into restoraunts (name, location) values ('Xenia', '8th Floor');
insert into restoraunts (name, location) values ('Daffy', 'Apt 329');
insert into restoraunts (name, location) values ('Shurwood', 'Room 575');
insert into restoraunts (name, location) values ('Clerc', '14th Floor');
insert into restoraunts (name, location) values ('Barri', '10th Floor');
insert into restoraunts (name, location) values ('Maribel', 'Suite 86');
insert into restoraunts (name, location) values ('Dane', 'Apt 17');
insert into restoraunts (name, location) values ('Evvie', 'Apt 357');
insert into restoraunts (name, location) values ('Sonja', 'Apt 434');
insert into restoraunts (name, location) values ('Rodge', '20th Floor');
insert into restoraunts (name, location) values ('Blayne', '18th Floor');
insert into restoraunts (name, location) values ('Tawnya', '5th Floor');
insert into restoraunts (name, location) values ('Blinni', '7th Floor');
insert into restoraunts (name, location) values ('Ky', 'Room 1507');
insert into restoraunts (name, location) values ('Kaela', 'Suite 38');
insert into restoraunts (name, location) values ('Free', '13th Floor');
insert into restoraunts (name, location) values ('Maynard', 'PO Box 82524');
insert into restoraunts (name, location) values ('Flem', '11th Floor');
insert into restoraunts (name, location) values ('Hester', 'Suite 43');
insert into restoraunts (name, location) values ('Elwood', 'Apt 815');
insert into restoraunts (name, location) values ('Norma', 'Apt 337');
insert into restoraunts (name, location) values ('Alena', '11th Floor');
insert into restoraunts (name, location) values ('Finley', 'Apt 1012');
insert into restoraunts (name, location) values ('Borden', 'Room 1755');
insert into restoraunts (name, location) values ('Conan', '9th Floor');
insert into restoraunts (name, location) values ('Augustin', 'Suite 59');
insert into restoraunts (name, location) values ('Gifford', 'PO Box 30710');
insert into restoraunts (name, location) values ('Ethelind', 'PO Box 40678');
insert into restoraunts (name, location) values ('Bartel', '6th Floor');
insert into restoraunts (name, location) values ('Emma', 'PO Box 63457');
insert into restoraunts (name, location) values ('Norrie', 'Apt 542');
insert into restoraunts (name, location) values ('Homere', 'PO Box 23642');
insert into restoraunts (name, location) values ('Alane', 'Apt 1568');
insert into restoraunts (name, location) values ('Winnifred', 'Suite 50');
insert into restoraunts (name, location) values ('Normand', 'PO Box 27709');
insert into restoraunts (name, location) values ('Hilliard', '10th Floor');
insert into restoraunts (name, location) values ('Corella', 'Suite 33');
insert into restoraunts (name, location) values ('Keefer', 'Room 1552');
insert into restoraunts (name, location) values ('Keelia', 'Apt 1435');
insert into restoraunts (name, location) values ('Mollie', '7th Floor');
insert into restoraunts (name, location) values ('Edsel', 'Apt 1638');
insert into restoraunts (name, location) values ('Idell', '15th Floor');
insert into restoraunts (name, location) values ('Tanhya', 'PO Box 17492');
insert into restoraunts (name, location) values ('Claudina', 'Room 909');
insert into restoraunts (name, location) values ('Estrellita', 'Room 1652');
insert into restoraunts (name, location) values ('Kalie', 'PO Box 76047');
insert into restoraunts (name, location) values ('Belle', '16th Floor');
insert into restoraunts (name, location) values ('Gary', 'Room 1996');
insert into restoraunts (name, location) values ('Ashby', 'Room 1637');
insert into restoraunts (name, location) values ('Valina', 'Apt 1452');
insert into restoraunts (name, location) values ('Monro', '17th Floor');
insert into restoraunts (name, location) values ('Wakefield', 'Room 1450');
insert into restoraunts (name, location) values ('Perl', 'Room 756');
insert into restoraunts (name, location) values ('Gar', 'PO Box 38875');
insert into restoraunts (name, location) values ('Allayne', 'Room 791');
insert into restoraunts (name, location) values ('Bret', 'Apt 1891');
insert into restoraunts (name, location) values ('Garreth', 'Apt 1247');
insert into restoraunts (name, location) values ('Terencio', 'Apt 883');
insert into restoraunts (name, location) values ('Maximilianus', 'Room 1529');
insert into restoraunts (name, location) values ('Kerrin', '7th Floor');
insert into restoraunts (name, location) values ('Emmalynn', '1st Floor');
insert into restoraunts (name, location) values ('Wandis', 'Room 1654');
insert into restoraunts (name, location) values ('Angil', 'Apt 1766');
insert into restoraunts (name, location) values ('Ludovico', 'Suite 27');
insert into restoraunts (name, location) values ('Raymund', 'PO Box 31202');
insert into restoraunts (name, location) values ('Salome', 'Apt 946');
insert into restoraunts (name, location) values ('Elissa', 'Room 1472');
insert into restoraunts (name, location) values ('Joshuah', 'PO Box 38583');
insert into restoraunts (name, location) values ('Lancelot', 'Apt 913');
insert into restoraunts (name, location) values ('Gunner', 'Suite 56');
insert into restoraunts (name, location) values ('Deva', '19th Floor');
insert into restoraunts (name, location) values ('Ulises', 'PO Box 3600');
insert into restoraunts (name, location) values ('Missy', 'Suite 83');
insert into restoraunts (name, location) values ('Krysta', 'Suite 82');
insert into restoraunts (name, location) values ('Fleming', 'Apt 1219');
insert into restoraunts (name, location) values ('Dorothee', 'Room 1253');
insert into restoraunts (name, location) values ('Birch', 'Room 1378');
insert into restoraunts (name, location) values ('Junie', 'PO Box 64587');
insert into restoraunts (name, location) values ('Nomi', 'PO Box 75778');
insert into restoraunts (name, location) values ('Bartie', '3rd Floor');
insert into restoraunts (name, location) values ('Dulciana', '13th Floor');
insert into restoraunts (name, location) values ('Loutitia', 'Room 962');
insert into restoraunts (name, location) values ('Stacee', 'Apt 635');
insert into restoraunts (name, location) values ('Nonna', 'Suite 33');
insert into restoraunts (name, location) values ('Dorine', 'Suite 21');
insert into restoraunts (name, location) values ('Goldina', '19th Floor');
insert into restoraunts (name, location) values ('Gerhardine', '19th Floor');
insert into restoraunts (name, location) values ('Millisent', 'PO Box 25487');
insert into restoraunts (name, location) values ('Franciskus', '4th Floor');
insert into restoraunts (name, location) values ('Romonda', 'Suite 40');
insert into restoraunts (name, location) values ('Liz', 'PO Box 11170');
insert into restoraunts (name, location) values ('Donna', 'Suite 66');
insert into restoraunts (name, location) values ('Ashely', 'Apt 1885');
insert into restoraunts (name, location) values ('Rachel', 'Apt 1450');
insert into restoraunts (name, location) values ('Freddy', 'Suite 63');
insert into restoraunts (name, location) values ('Catherin', 'Apt 1706');
insert into restoraunts (name, location) values ('Jasmin', '19th Floor');
insert into restoraunts (name, location) values ('Estel', 'Apt 680');
insert into restoraunts (name, location) values ('Betta', 'Room 248');
insert into restoraunts (name, location) values ('Felic', 'PO Box 38148');
insert into restoraunts (name, location) values ('Sinclare', '4th Floor');
insert into restoraunts (name, location) values ('Eldredge', 'PO Box 78389');
insert into restoraunts (name, location) values ('Sari', 'Suite 14');
insert into restoraunts (name, location) values ('Dion', '10th Floor');
insert into restoraunts (name, location) values ('Trula', 'Room 982');
insert into restoraunts (name, location) values ('Donall', 'PO Box 83772');
insert into restoraunts (name, location) values ('Merle', '14th Floor');
insert into restoraunts (name, location) values ('Ulrich', 'Room 907');
insert into restoraunts (name, location) values ('Archibaldo', 'PO Box 75835');
insert into restoraunts (name, location) values ('Manny', 'PO Box 73508');
insert into restoraunts (name, location) values ('Dante', 'Apt 1239');
insert into restoraunts (name, location) values ('Roman', 'Suite 19');
insert into restoraunts (name, location) values ('Katherine', 'Suite 10');
insert into restoraunts (name, location) values ('Anabel', '11th Floor');
insert into restoraunts (name, location) values ('Lief', '1st Floor');
insert into restoraunts (name, location) values ('Rosie', 'Room 706');
insert into restoraunts (name, location) values ('Spence', 'Room 1102');
insert into restoraunts (name, location) values ('Cecily', 'Apt 757');
insert into restoraunts (name, location) values ('Adel', '6th Floor');
insert into restoraunts (name, location) values ('Aurelea', '14th Floor');
insert into restoraunts (name, location) values ('Talbert', 'Apt 586');
insert into restoraunts (name, location) values ('Iolande', 'Apt 1632');
insert into restoraunts (name, location) values ('Vicky', 'Suite 78');
insert into restoraunts (name, location) values ('Constantino', 'Room 224');
insert into restoraunts (name, location) values ('Tammi', '13th Floor');
insert into restoraunts (name, location) values ('Domeniga', 'PO Box 39768');
insert into restoraunts (name, location) values ('Ryley', '6th Floor');
insert into restoraunts (name, location) values ('Falito', 'Apt 1685');
insert into restoraunts (name, location) values ('Pepe', '15th Floor');
insert into restoraunts (name, location) values ('Cordell', 'Suite 43');
insert into restoraunts (name, location) values ('Ewen', 'Room 1921');
insert into restoraunts (name, location) values ('Calhoun', 'Apt 588');
insert into restoraunts (name, location) values ('Frederica', 'Apt 1864');
insert into restoraunts (name, location) values ('Jeno', 'Room 550');
insert into restoraunts (name, location) values ('Feodora', 'Suite 85');
insert into restoraunts (name, location) values ('Cindelyn', 'Suite 44');
insert into restoraunts (name, location) values ('Michele', 'Suite 58');
insert into restoraunts (name, location) values ('Felicle', 'Room 933');
insert into restoraunts (name, location) values ('Max', 'Apt 1147');
insert into restoraunts (name, location) values ('Mathilde', 'PO Box 68062');
insert into restoraunts (name, location) values ('Sullivan', '1st Floor');
insert into restoraunts (name, location) values ('Hakim', 'Suite 80');
insert into restoraunts (name, location) values ('Hurleigh', 'Room 831');
insert into restoraunts (name, location) values ('Bartolemo', 'Suite 30');
insert into restoraunts (name, location) values ('Christie', 'Apt 1036');
insert into restoraunts (name, location) values ('Shalna', 'PO Box 47336');
insert into restoraunts (name, location) values ('Abigael', 'Room 1021');
insert into restoraunts (name, location) values ('Breanne', 'Room 518');
insert into restoraunts (name, location) values ('Benoit', 'PO Box 64224');
insert into restoraunts (name, location) values ('Harriette', 'Room 1105');
insert into restoraunts (name, location) values ('Jermayne', 'PO Box 95401');
insert into restoraunts (name, location) values ('Geno', 'PO Box 31277');
insert into restoraunts (name, location) values ('Denni', 'Suite 70');
insert into restoraunts (name, location) values ('Jerrome', 'Suite 43');
insert into restoraunts (name, location) values ('Boonie', 'Apt 275');
insert into restoraunts (name, location) values ('Frasier', 'Apt 299');
insert into restoraunts (name, location) values ('Herby', 'Suite 71');
insert into restoraunts (name, location) values ('Clywd', 'Suite 35');
insert into restoraunts (name, location) values ('Hermie', 'Suite 11');
insert into restoraunts (name, location) values ('Nada', '8th Floor');
insert into restoraunts (name, location) values ('Ivar', 'Suite 13');
insert into restoraunts (name, location) values ('Randy', 'Room 1612');
insert into restoraunts (name, location) values ('Minor', '3rd Floor');
insert into restoraunts (name, location) values ('Lalo', 'Suite 42');
insert into restoraunts (name, location) values ('Skippy', 'PO Box 58291');
insert into restoraunts (name, location) values ('Arline', 'Suite 12');
insert into restoraunts (name, location) values ('Chucho', 'Room 138');
insert into restoraunts (name, location) values ('Fletcher', 'Apt 156');
insert into restoraunts (name, location) values ('Kathryne', 'Room 1053');
insert into restoraunts (name, location) values ('Fedora', 'Suite 1');
insert into restoraunts (name, location) values ('Catlee', 'Apt 1388');
insert into restoraunts (name, location) values ('Sax', 'Suite 40');
insert into restoraunts (name, location) values ('Nanci', 'Room 819');
insert into restoraunts (name, location) values ('Bryn', 'Room 1072');
insert into restoraunts (name, location) values ('Gerri', '16th Floor');
insert into restoraunts (name, location) values ('Rhys', 'Suite 6');
insert into restoraunts (name, location) values ('Matilde', 'Room 1550');
insert into restoraunts (name, location) values ('Ibbie', 'Suite 22');
insert into restoraunts (name, location) values ('Zaria', 'Apt 1889');
insert into restoraunts (name, location) values ('Alissa', 'Suite 2');
insert into restoraunts (name, location) values ('Violet', 'Suite 88');
insert into restoraunts (name, location) values ('Jenn', 'Apt 726');
insert into restoraunts (name, location) values ('Elaina', 'Apt 1869');
insert into restoraunts (name, location) values ('Neale', 'Room 978');
insert into restoraunts (name, location) values ('Amalie', 'Room 1402');
insert into restoraunts (name, location) values ('Dollie', 'Suite 26');
insert into restoraunts (name, location) values ('Theodoric', 'PO Box 93731');
insert into restoraunts (name, location) values ('Andrew', 'Room 1293');
insert into restoraunts (name, location) values ('Jackson', '3rd Floor');
insert into restoraunts (name, location) values ('Haslett', '5th Floor');
insert into restoraunts (name, location) values ('Vivi', 'Room 592');
insert into restoraunts (name, location) values ('Lamont', 'Room 1633');
insert into restoraunts (name, location) values ('Jamie', 'Apt 1957');
insert into restoraunts (name, location) values ('Haroun', 'PO Box 73711');
insert into restoraunts (name, location) values ('Geordie', '7th Floor');
insert into restoraunts (name, location) values ('Ava', 'Room 1472');
insert into restoraunts (name, location) values ('Cleve', 'Suite 37');
insert into restoraunts (name, location) values ('Fredelia', 'Room 693');
insert into restoraunts (name, location) values ('Aili', 'Apt 1082');
insert into restoraunts (name, location) values ('Dunstan', 'Apt 237');
insert into restoraunts (name, location) values ('Kahlil', '12th Floor');
insert into restoraunts (name, location) values ('Kara-lynn', 'Suite 37');
insert into restoraunts (name, location) values ('Kingsly', 'Room 1919');
insert into restoraunts (name, location) values ('Mead', 'Room 1550');
insert into restoraunts (name, location) values ('Portia', 'Apt 1480');
insert into restoraunts (name, location) values ('Joshia', 'Room 1928');
insert into restoraunts (name, location) values ('Garrett', 'PO Box 97262');
insert into restoraunts (name, location) values ('Thorny', 'Apt 1936');
insert into restoraunts (name, location) values ('Sigfried', 'Apt 479');
insert into restoraunts (name, location) values ('Cassondra', 'Room 1729');
insert into restoraunts (name, location) values ('Thorin', 'Suite 66');
insert into restoraunts (name, location) values ('Errick', 'Room 333');
insert into restoraunts (name, location) values ('Greg', 'PO Box 43221');
insert into restoraunts (name, location) values ('Charity', 'Room 1145');
insert into restoraunts (name, location) values ('Karia', 'PO Box 94476');
insert into restoraunts (name, location) values ('Clemens', 'Room 957');
insert into restoraunts (name, location) values ('Blanch', 'Room 66');
insert into restoraunts (name, location) values ('Yulma', '7th Floor');
insert into restoraunts (name, location) values ('Katti', 'Room 618');
insert into restoraunts (name, location) values ('Carly', '10th Floor');
insert into restoraunts (name, location) values ('Vikki', 'Suite 67');
insert into restoraunts (name, location) values ('Sherill', 'Room 720');
insert into restoraunts (name, location) values ('Cyrus', 'Room 192');
insert into restoraunts (name, location) values ('Hephzibah', '12th Floor');
insert into restoraunts (name, location) values ('Grannie', 'PO Box 31583');
insert into restoraunts (name, location) values ('Florentia', '20th Floor');
insert into restoraunts (name, location) values ('Sileas', 'Suite 92');
insert into restoraunts (name, location) values ('Harrietta', 'Room 1059');
insert into restoraunts (name, location) values ('Sigfried', 'PO Box 14537');
insert into restoraunts (name, location) values ('Ardine', 'Suite 50');
insert into restoraunts (name, location) values ('Godfrey', '9th Floor');
insert into restoraunts (name, location) values ('Dunn', 'Apt 282');
insert into restoraunts (name, location) values ('Reiko', 'Room 458');
insert into restoraunts (name, location) values ('Inglebert', 'Room 1469');
insert into restoraunts (name, location) values ('Petrina', 'Apt 375');
insert into restoraunts (name, location) values ('Lenna', 'PO Box 63952');
insert into restoraunts (name, location) values ('Janek', 'Apt 1721');
insert into restoraunts (name, location) values ('Julianne', 'Room 1221');
insert into restoraunts (name, location) values ('Laina', 'Room 1393');
insert into restoraunts (name, location) values ('Harrietta', 'Room 1565');
insert into restoraunts (name, location) values ('Phaedra', 'Apt 1704');
insert into restoraunts (name, location) values ('Marja', 'Apt 1730');
insert into restoraunts (name, location) values ('Gav', '14th Floor');
insert into restoraunts (name, location) values ('Hana', 'Room 1592');
insert into restoraunts (name, location) values ('Isis', 'Apt 719');
insert into restoraunts (name, location) values ('Lodovico', 'Apt 1278');
insert into restoraunts (name, location) values ('Kare', 'PO Box 94174');
insert into restoraunts (name, location) values ('Jamie', '20th Floor');
insert into restoraunts (name, location) values ('Alla', 'Suite 30');
insert into restoraunts (name, location) values ('Cornela', 'PO Box 17597');
insert into restoraunts (name, location) values ('Pavla', 'Apt 438');
insert into restoraunts (name, location) values ('Parrnell', 'Room 1020');
insert into restoraunts (name, location) values ('Mandi', 'Suite 62');
insert into restoraunts (name, location) values ('Storm', 'Room 1806');
insert into restoraunts (name, location) values ('Corena', '19th Floor');
insert into restoraunts (name, location) values ('Hillie', 'Suite 79');
insert into restoraunts (name, location) values ('Lurette', 'Suite 99');
insert into restoraunts (name, location) values ('Zorah', 'Suite 45');
insert into restoraunts (name, location) values ('Florrie', '8th Floor');
insert into restoraunts (name, location) values ('Georgina', 'Room 163');
insert into restoraunts (name, location) values ('Cassey', 'PO Box 11110');
insert into restoraunts (name, location) values ('Andrei', 'Apt 413');
insert into restoraunts (name, location) values ('Cris', 'PO Box 10781');
insert into restoraunts (name, location) values ('Giles', 'Apt 705');
insert into restoraunts (name, location) values ('Ynez', '19th Floor');
insert into restoraunts (name, location) values ('Anthe', 'Apt 23');
insert into restoraunts (name, location) values ('Tracee', 'PO Box 62566');
insert into restoraunts (name, location) values ('Olin', 'PO Box 13917');
insert into restoraunts (name, location) values ('Lexie', 'PO Box 69245');
insert into restoraunts (name, location) values ('Hillie', 'Apt 262');
insert into restoraunts (name, location) values ('Lucio', 'Suite 70');
insert into restoraunts (name, location) values ('Olive', 'Apt 1385');
insert into restoraunts (name, location) values ('Web', 'Suite 17');
insert into restoraunts (name, location) values ('Thedric', 'Room 1784');
insert into restoraunts (name, location) values ('Arluene', 'PO Box 45953');
insert into restoraunts (name, location) values ('Aurelia', 'Suite 61');
insert into restoraunts (name, location) values ('Padraig', '9th Floor');
insert into restoraunts (name, location) values ('Vonni', '6th Floor');
insert into restoraunts (name, location) values ('Husain', 'PO Box 67244');
insert into restoraunts (name, location) values ('Nahum', 'PO Box 27239');
insert into restoraunts (name, location) values ('Etta', 'PO Box 93114');
insert into restoraunts (name, location) values ('Nicola', '15th Floor');
insert into restoraunts (name, location) values ('Cynthea', '3rd Floor');
insert into restoraunts (name, location) values ('Oren', 'Suite 72');
insert into restoraunts (name, location) values ('Dorelle', 'Room 1505');
insert into restoraunts (name, location) values ('Paten', 'PO Box 14502');
insert into restoraunts (name, location) values ('Ludvig', '17th Floor');
insert into restoraunts (name, location) values ('Gilberte', 'PO Box 42281');
insert into restoraunts (name, location) values ('Calli', 'Suite 34');
insert into restoraunts (name, location) values ('Rudolfo', 'Apt 162');
insert into restoraunts (name, location) values ('Torey', 'Room 1780');
insert into restoraunts (name, location) values ('Nikolai', 'PO Box 85080');
insert into restoraunts (name, location) values ('Zena', 'Room 1398');
insert into restoraunts (name, location) values ('Willabella', 'Room 760');
insert into restoraunts (name, location) values ('Haley', 'Apt 170');
insert into restoraunts (name, location) values ('Joe', 'PO Box 69117');
insert into restoraunts (name, location) values ('Berny', 'Suite 93');
insert into restoraunts (name, location) values ('Bobbee', 'PO Box 18192');
insert into restoraunts (name, location) values ('Margarette', '5th Floor');
insert into restoraunts (name, location) values ('Torry', 'Apt 305');
insert into restoraunts (name, location) values ('Ben', 'PO Box 65637');
insert into restoraunts (name, location) values ('Adolf', 'Apt 994');
insert into restoraunts (name, location) values ('Bryan', '18th Floor');
insert into restoraunts (name, location) values ('Nona', 'Room 248');
insert into restoraunts (name, location) values ('Jorrie', 'PO Box 3534');
insert into restoraunts (name, location) values ('Staci', 'Room 1433');
insert into restoraunts (name, location) values ('Hortense', 'PO Box 77855');
insert into restoraunts (name, location) values ('Joly', 'PO Box 81822');
insert into restoraunts (name, location) values ('Lonnard', 'Apt 86');
insert into restoraunts (name, location) values ('Kylie', 'Apt 8');
insert into restoraunts (name, location) values ('Arni', 'Apt 1948');
insert into restoraunts (name, location) values ('Anica', 'Apt 1560');
insert into restoraunts (name, location) values ('Den', 'Room 589');
insert into restoraunts (name, location) values ('Austin', '19th Floor');
insert into restoraunts (name, location) values ('Marni', 'PO Box 500');
insert into restoraunts (name, location) values ('Kirby', 'Suite 66');
insert into restoraunts (name, location) values ('Harper', 'Room 323');
insert into restoraunts (name, location) values ('Faythe', '4th Floor');
insert into restoraunts (name, location) values ('Ransell', 'Apt 292');
insert into restoraunts (name, location) values ('Sherm', 'PO Box 67358');
insert into restoraunts (name, location) values ('Mariann', 'Suite 4');
insert into restoraunts (name, location) values ('Leesa', 'Apt 1047');
insert into restoraunts (name, location) values ('Melitta', 'Suite 99');
insert into restoraunts (name, location) values ('Gavra', 'PO Box 61832');
insert into restoraunts (name, location) values ('Shandie', 'PO Box 6778');
insert into restoraunts (name, location) values ('Bobbie', '5th Floor');
insert into restoraunts (name, location) values ('Babette', 'Apt 1545');
insert into restoraunts (name, location) values ('Cybil', 'Apt 1838');
insert into restoraunts (name, location) values ('Caspar', 'Suite 73');
insert into restoraunts (name, location) values ('Tabbi', 'Room 854');
insert into restoraunts (name, location) values ('Sigmund', 'PO Box 47519');
insert into restoraunts (name, location) values ('Conan', 'Suite 8');
insert into restoraunts (name, location) values ('Hobard', 'Apt 13');
insert into restoraunts (name, location) values ('Brucie', 'Suite 78');
insert into restoraunts (name, location) values ('Efren', 'PO Box 70531');
insert into restoraunts (name, location) values ('Padgett', '10th Floor');
insert into restoraunts (name, location) values ('Antony', 'PO Box 81628');
insert into restoraunts (name, location) values ('Mike', 'PO Box 81165');
insert into restoraunts (name, location) values ('Noellyn', 'Apt 851');
insert into restoraunts (name, location) values ('Ileana', 'Room 640');
insert into restoraunts (name, location) values ('Sawyere', '6th Floor');
insert into restoraunts (name, location) values ('Kevon', 'Suite 11');
insert into restoraunts (name, location) values ('Katerine', 'PO Box 16853');
insert into restoraunts (name, location) values ('Berne', 'Apt 640');
insert into restoraunts (name, location) values ('Nye', 'Apt 1894');
insert into restoraunts (name, location) values ('Hank', 'Suite 18');
insert into restoraunts (name, location) values ('Tobe', 'Room 740');
insert into restoraunts (name, location) values ('Fleurette', 'PO Box 83298');
insert into restoraunts (name, location) values ('Cyb', 'Room 1636');
insert into restoraunts (name, location) values ('Zea', '7th Floor');
insert into restoraunts (name, location) values ('Mylo', 'Apt 8');
insert into restoraunts (name, location) values ('Dasie', 'Apt 665');
insert into restoraunts (name, location) values ('Tamqrah', 'PO Box 35278');
insert into restoraunts (name, location) values ('Lanny', 'Apt 1606');
insert into restoraunts (name, location) values ('Byrann', 'Apt 1467');
insert into restoraunts (name, location) values ('Linnet', 'Room 842');
insert into restoraunts (name, location) values ('Brucie', 'PO Box 19543');
insert into restoraunts (name, location) values ('Hakim', 'Suite 41');
insert into restoraunts (name, location) values ('Alethea', '20th Floor');
insert into restoraunts (name, location) values ('Vidovik', 'Apt 1031');
insert into restoraunts (name, location) values ('Malissia', 'PO Box 749');
insert into restoraunts (name, location) values ('Marlee', '1st Floor');
insert into restoraunts (name, location) values ('Sheela', 'Apt 1795');
insert into restoraunts (name, location) values ('Cort', 'Suite 14');
insert into restoraunts (name, location) values ('Tressa', 'Suite 36');
insert into restoraunts (name, location) values ('Deane', 'Suite 75');
insert into restoraunts (name, location) values ('Katharyn', 'Room 1590');
insert into restoraunts (name, location) values ('Shaylah', 'PO Box 25365');
insert into restoraunts (name, location) values ('Brnaby', 'Apt 566');
insert into restoraunts (name, location) values ('Gates', 'Room 1958');
insert into restoraunts (name, location) values ('Ardyce', 'Suite 1');
insert into restoraunts (name, location) values ('Geraldine', 'PO Box 14636');
insert into restoraunts (name, location) values ('Jaquenetta', 'Room 1358');
insert into restoraunts (name, location) values ('Dolley', 'Room 85');
insert into restoraunts (name, location) values ('Flore', 'Room 618');
insert into restoraunts (name, location) values ('Kassandra', 'Apt 1611');
insert into restoraunts (name, location) values ('Anthony', 'Suite 9');
insert into restoraunts (name, location) values ('Arvin', 'PO Box 73941');
insert into restoraunts (name, location) values ('Culley', 'Room 125');
insert into restoraunts (name, location) values ('Fidole', '2nd Floor');
insert into restoraunts (name, location) values ('Dunc', 'PO Box 63373');
insert into restoraunts (name, location) values ('Bank', 'Room 1279');
insert into restoraunts (name, location) values ('Dani', 'PO Box 47024');
insert into restoraunts (name, location) values ('Alverta', 'PO Box 70363');
insert into restoraunts (name, location) values ('Davey', 'Room 1593');
insert into restoraunts (name, location) values ('Rea', 'Room 1779');
insert into restoraunts (name, location) values ('Collen', '2nd Floor');
insert into restoraunts (name, location) values ('Jaymie', 'PO Box 67421');
insert into restoraunts (name, location) values ('Ulrich', '5th Floor');
insert into restoraunts (name, location) values ('Dorothy', 'Suite 77');
insert into restoraunts (name, location) values ('Jordain', 'Room 110');
insert into restoraunts (name, location) values ('Ester', '4th Floor');
insert into restoraunts (name, location) values ('Woodie', 'Room 1170');
insert into restoraunts (name, location) values ('Laverna', 'Room 477');
insert into restoraunts (name, location) values ('Sibley', 'Apt 1506');
insert into restoraunts (name, location) values ('Carmencita', 'Suite 24');
insert into restoraunts (name, location) values ('Josefa', '5th Floor');
insert into restoraunts (name, location) values ('Alric', 'PO Box 73658');
insert into restoraunts (name, location) values ('Madlin', 'PO Box 89763');
insert into restoraunts (name, location) values ('Cad', '2nd Floor');
insert into restoraunts (name, location) values ('Oralia', 'Apt 1063');
insert into restoraunts (name, location) values ('Laurence', 'PO Box 92047');
insert into restoraunts (name, location) values ('Luis', 'PO Box 46883');
insert into restoraunts (name, location) values ('Ephraim', 'PO Box 75396');
insert into restoraunts (name, location) values ('Jaclin', 'Suite 32');
insert into restoraunts (name, location) values ('Nadya', 'PO Box 99656');
insert into restoraunts (name, location) values ('Charlena', 'Room 773');
insert into restoraunts (name, location) values ('Guenna', 'Room 1133');
insert into restoraunts (name, location) values ('Marjory', 'Suite 60');
insert into restoraunts (name, location) values ('Patten', 'Apt 1487');
insert into restoraunts (name, location) values ('Abel', '2nd Floor');
insert into restoraunts (name, location) values ('Herb', 'Room 1954');
insert into restoraunts (name, location) values ('Vivian', 'Suite 35');
insert into restoraunts (name, location) values ('Chick', 'Room 110');
insert into restoraunts (name, location) values ('Rodrique', '7th Floor');
insert into restoraunts (name, location) values ('Laverne', 'Room 1875');
insert into restoraunts (name, location) values ('Klement', 'Room 1351');
insert into restoraunts (name, location) values ('Aldridge', 'Apt 914');
insert into restoraunts (name, location) values ('Katinka', '20th Floor');
insert into restoraunts (name, location) values ('Waiter', 'Apt 1243');
insert into restoraunts (name, location) values ('Francis', 'Room 1068');
insert into restoraunts (name, location) values ('Danie', '1st Floor');
insert into restoraunts (name, location) values ('Moreen', 'Suite 32');
insert into restoraunts (name, location) values ('Howie', 'Room 206');
insert into restoraunts (name, location) values ('Kit', 'Room 1626');
insert into restoraunts (name, location) values ('Ruprecht', 'Suite 80');
insert into restoraunts (name, location) values ('Vite', 'Room 756');
insert into restoraunts (name, location) values ('Daren', 'PO Box 15693');
insert into restoraunts (name, location) values ('Odele', 'Room 1339');
insert into restoraunts (name, location) values ('Ervin', 'Suite 55');
insert into restoraunts (name, location) values ('Mercedes', 'Apt 1375');
insert into restoraunts (name, location) values ('Janos', 'Apt 1570');
insert into restoraunts (name, location) values ('Wayland', 'Room 1711');
insert into restoraunts (name, location) values ('Ibrahim', 'Suite 94');
insert into restoraunts (name, location) values ('Garik', 'Apt 1220');
insert into restoraunts (name, location) values ('Denni', 'Apt 1239');
insert into restoraunts (name, location) values ('Dwight', 'PO Box 42824');
insert into restoraunts (name, location) values ('Sam', 'Apt 1624');
insert into restoraunts (name, location) values ('Tabbie', 'Suite 64');
insert into restoraunts (name, location) values ('Carlita', 'Apt 503');
insert into restoraunts (name, location) values ('Cherida', 'Apt 1475');
insert into restoraunts (name, location) values ('Norene', 'PO Box 64449');
insert into restoraunts (name, location) values ('Pam', '19th Floor');
insert into restoraunts (name, location) values ('Nissa', 'Apt 700');
insert into restoraunts (name, location) values ('Van', '9th Floor');
insert into restoraunts (name, location) values ('Alvy', 'PO Box 5058');
insert into restoraunts (name, location) values ('Alan', 'Room 1431');
insert into restoraunts (name, location) values ('Cherri', 'PO Box 50351');
insert into restoraunts (name, location) values ('Godfree', 'PO Box 223');
insert into restoraunts (name, location) values ('Saunder', 'PO Box 6639');
insert into restoraunts (name, location) values ('Karlotte', 'Apt 770');
insert into restoraunts (name, location) values ('Ephrayim', '9th Floor');
insert into restoraunts (name, location) values ('Orlando', 'Apt 1294');
insert into restoraunts (name, location) values ('Dionis', 'Room 824');
insert into restoraunts (name, location) values ('Lettie', 'Room 1268');
insert into restoraunts (name, location) values ('Georg', 'PO Box 17930');
insert into restoraunts (name, location) values ('Hersh', 'Room 1464');
insert into restoraunts (name, location) values ('Rickie', 'Apt 1513');
insert into restoraunts (name, location) values ('Heather', 'Apt 369');
insert into restoraunts (name, location) values ('Bartholomeus', 'Apt 975');
insert into restoraunts (name, location) values ('Keene', 'Room 714');
insert into restoraunts (name, location) values ('Fredia', '5th Floor');
insert into restoraunts (name, location) values ('Gordan', 'Room 1152');
insert into restoraunts (name, location) values ('Jehu', '18th Floor');
insert into restoraunts (name, location) values ('Cassondra', 'PO Box 30257');
insert into restoraunts (name, location) values ('Miguelita', 'Suite 71');
insert into restoraunts (name, location) values ('Elijah', 'Room 725');
insert into restoraunts (name, location) values ('Peadar', '20th Floor');
insert into restoraunts (name, location) values ('Rey', 'Suite 84');
insert into restoraunts (name, location) values ('Bili', 'Room 1235');
insert into restoraunts (name, location) values ('Manya', 'Room 677');
insert into restoraunts (name, location) values ('Kassi', 'Apt 519');
insert into restoraunts (name, location) values ('Alisha', '1st Floor');
insert into restoraunts (name, location) values ('Alden', 'Apt 1545');
insert into restoraunts (name, location) values ('Keeley', 'Apt 475');
insert into restoraunts (name, location) values ('Christoforo', 'Room 215');
insert into restoraunts (name, location) values ('Lucille', 'PO Box 44925');
insert into restoraunts (name, location) values ('Torrin', 'PO Box 63054');
insert into restoraunts (name, location) values ('Mercy', '17th Floor');
insert into restoraunts (name, location) values ('Denny', 'Apt 1923');
insert into restoraunts (name, location) values ('Darcy', 'Suite 71');
insert into restoraunts (name, location) values ('Matty', 'Room 841');
insert into restoraunts (name, location) values ('Cherilynn', 'Room 699');
insert into restoraunts (name, location) values ('Aurel', 'Apt 1154');
insert into restoraunts (name, location) values ('Lola', 'PO Box 74424');
insert into restoraunts (name, location) values ('Marjorie', 'Suite 10');
insert into restoraunts (name, location) values ('Maxy', 'Suite 2');
insert into restoraunts (name, location) values ('Golda', 'Suite 47');
insert into restoraunts (name, location) values ('Terrel', 'Apt 1237');
insert into restoraunts (name, location) values ('Bartolomeo', 'PO Box 90952');
insert into restoraunts (name, location) values ('Marris', 'Room 1355');
insert into restoraunts (name, location) values ('Nikoletta', 'Room 79');
insert into restoraunts (name, location) values ('Gwenore', '8th Floor');
insert into restoraunts (name, location) values ('Kathie', 'Apt 874');
insert into restoraunts (name, location) values ('Charles', '3rd Floor');
insert into restoraunts (name, location) values ('Daryl', 'Apt 1002');
insert into restoraunts (name, location) values ('Rayshell', 'Apt 864');
insert into restoraunts (name, location) values ('Uriah', 'Apt 315');
insert into restoraunts (name, location) values ('Justino', 'Apt 1673');
insert into restoraunts (name, location) values ('Corilla', 'Suite 68');
insert into restoraunts (name, location) values ('De witt', 'Room 1130');
insert into restoraunts (name, location) values ('Reba', 'PO Box 20908');
insert into restoraunts (name, location) values ('Archambault', 'Room 1267');
insert into restoraunts (name, location) values ('Artus', '5th Floor');
insert into restoraunts (name, location) values ('Alec', '14th Floor');
insert into restoraunts (name, location) values ('Kerr', 'Apt 196');
insert into restoraunts (name, location) values ('Ivar', 'Apt 995');
insert into restoraunts (name, location) values ('Gardie', 'Room 119');
insert into restoraunts (name, location) values ('Roddie', 'PO Box 32737');
insert into restoraunts (name, location) values ('Sergent', 'Suite 60');
insert into restoraunts (name, location) values ('Kessia', 'Room 343');
insert into restoraunts (name, location) values ('Erskine', '17th Floor');
insert into restoraunts (name, location) values ('Noelle', '17th Floor');
insert into restoraunts (name, location) values ('Keefer', 'PO Box 83532');
insert into restoraunts (name, location) values ('Otha', 'Room 388');
insert into restoraunts (name, location) values ('Gelya', 'Suite 19');
insert into restoraunts (name, location) values ('Sonnnie', 'PO Box 98186');
insert into restoraunts (name, location) values ('Ainslie', 'Apt 1432');
insert into restoraunts (name, location) values ('Keene', 'Apt 248');
insert into restoraunts (name, location) values ('Calli', 'Suite 72');
insert into restoraunts (name, location) values ('Dominik', 'Room 617');
insert into restoraunts (name, location) values ('Chelsea', 'PO Box 49656');
insert into restoraunts (name, location) values ('Geneva', '17th Floor');
insert into restoraunts (name, location) values ('Lothario', 'Suite 36');
insert into restoraunts (name, location) values ('Korella', 'PO Box 68698');
insert into restoraunts (name, location) values ('Pollyanna', 'Apt 37');
insert into restoraunts (name, location) values ('Noby', 'Suite 6');
insert into restoraunts (name, location) values ('Faustina', 'Apt 1422');
insert into restoraunts (name, location) values ('Morgen', 'PO Box 30850');
insert into restoraunts (name, location) values ('Dario', 'PO Box 2752');
insert into restoraunts (name, location) values ('Tara', 'Suite 82');
insert into restoraunts (name, location) values ('Allison', 'PO Box 95577');
insert into restoraunts (name, location) values ('Katya', 'Room 545');
insert into restoraunts (name, location) values ('Dorisa', 'PO Box 39381');
insert into restoraunts (name, location) values ('Cello', 'PO Box 559');
insert into restoraunts (name, location) values ('Eleni', 'Apt 401');
insert into restoraunts (name, location) values ('Berkly', 'Suite 34');
insert into restoraunts (name, location) values ('Ilyssa', '16th Floor');
insert into restoraunts (name, location) values ('Andee', '1st Floor');
insert into restoraunts (name, location) values ('Cesare', 'PO Box 2498');
insert into restoraunts (name, location) values ('Perren', '6th Floor');
insert into restoraunts (name, location) values ('Sheree', 'Room 1604');
insert into restoraunts (name, location) values ('Arvie', 'Suite 41');
insert into restoraunts (name, location) values ('Adriena', 'PO Box 74527');
insert into restoraunts (name, location) values ('Koo', 'Room 766');
insert into restoraunts (name, location) values ('Zelda', '11th Floor');
insert into restoraunts (name, location) values ('Kelly', 'Suite 21');
insert into restoraunts (name, location) values ('Blondelle', 'PO Box 46775');
insert into restoraunts (name, location) values ('Belvia', 'Room 159');
insert into restoraunts (name, location) values ('Lawton', 'Suite 77');
insert into restoraunts (name, location) values ('Travis', 'Apt 701');
insert into restoraunts (name, location) values ('Maureen', '4th Floor');
insert into restoraunts (name, location) values ('Calypso', '6th Floor');
insert into restoraunts (name, location) values ('Rhys', '19th Floor');
insert into restoraunts (name, location) values ('Phillipp', 'Room 1464');
insert into restoraunts (name, location) values ('Gabie', 'Suite 64');
insert into restoraunts (name, location) values ('Jarrid', 'PO Box 56557');
insert into restoraunts (name, location) values ('Archibaldo', 'PO Box 99935');
insert into restoraunts (name, location) values ('Gwenneth', 'Room 1660');
insert into restoraunts (name, location) values ('Avivah', 'Apt 803');
insert into restoraunts (name, location) values ('Wain', 'Suite 47');
insert into restoraunts (name, location) values ('Klement', 'Suite 73');
insert into restoraunts (name, location) values ('Larissa', '3rd Floor');
insert into restoraunts (name, location) values ('Karoly', 'Apt 1182');
insert into restoraunts (name, location) values ('Philbert', 'PO Box 49655');
insert into restoraunts (name, location) values ('Ilse', 'Suite 84');
insert into restoraunts (name, location) values ('Dollie', 'PO Box 74529');
insert into restoraunts (name, location) values ('Ewan', 'Suite 33');
insert into restoraunts (name, location) values ('Catarina', 'Room 153');
insert into restoraunts (name, location) values ('Nicoline', '10th Floor');
insert into restoraunts (name, location) values ('Hermia', 'Apt 394');
insert into restoraunts (name, location) values ('Shayla', 'Room 1852');
insert into restoraunts (name, location) values ('Ophelie', 'PO Box 92582');
insert into restoraunts (name, location) values ('Stuart', 'Room 241');
insert into restoraunts (name, location) values ('Nona', 'PO Box 65051');
insert into restoraunts (name, location) values ('Isabelle', 'Suite 81');
insert into restoraunts (name, location) values ('Maggi', 'Suite 73');
insert into restoraunts (name, location) values ('Faun', 'Room 978');
insert into restoraunts (name, location) values ('Juliann', 'Apt 1312');
insert into restoraunts (name, location) values ('Marian', 'Room 238');
insert into restoraunts (name, location) values ('Gweneth', '8th Floor');
insert into restoraunts (name, location) values ('Benedikt', 'PO Box 81054');
insert into restoraunts (name, location) values ('Beatrix', '6th Floor');
insert into restoraunts (name, location) values ('Emmerich', 'Apt 625');
insert into restoraunts (name, location) values ('Lin', 'Suite 44');
insert into restoraunts (name, location) values ('Evangelia', 'Room 1740');
insert into restoraunts (name, location) values ('Peterus', 'Room 1181');
insert into restoraunts (name, location) values ('Cyrus', 'Apt 409');
insert into restoraunts (name, location) values ('Zeb', '16th Floor');
insert into restoraunts (name, location) values ('Lemmie', 'Apt 1036');
insert into restoraunts (name, location) values ('Brendon', 'Suite 27');
insert into restoraunts (name, location) values ('Bud', 'Apt 987');
insert into restoraunts (name, location) values ('Jacenta', '13th Floor');
insert into restoraunts (name, location) values ('Leta', '11th Floor');
insert into restoraunts (name, location) values ('Dorree', 'Suite 86');
insert into restoraunts (name, location) values ('Pearline', 'Suite 29');
insert into restoraunts (name, location) values ('Sergent', 'Apt 1933');
insert into restoraunts (name, location) values ('Mallissa', 'Apt 1011');
insert into restoraunts (name, location) values ('Carlos', 'Room 1535');
insert into restoraunts (name, location) values ('Leonore', 'Suite 62');
insert into restoraunts (name, location) values ('Gabi', '10th Floor');
insert into restoraunts (name, location) values ('Abba', 'PO Box 3902');
insert into restoraunts (name, location) values ('Gwenora', '11th Floor');
insert into restoraunts (name, location) values ('Marleen', '10th Floor');
insert into restoraunts (name, location) values ('Chuck', '6th Floor');
insert into restoraunts (name, location) values ('Nerita', 'Suite 29');
insert into restoraunts (name, location) values ('Obidiah', 'Apt 131');
insert into restoraunts (name, location) values ('Pacorro', 'PO Box 5651');
insert into restoraunts (name, location) values ('Lotti', '9th Floor');
insert into restoraunts (name, location) values ('Clement', 'PO Box 95825');
insert into restoraunts (name, location) values ('Bernadette', 'Suite 60');
insert into restoraunts (name, location) values ('Siegfried', 'Suite 88');
insert into restoraunts (name, location) values ('Englebert', 'Suite 53');
insert into restoraunts (name, location) values ('Isidor', '14th Floor');
insert into restoraunts (name, location) values ('Alexandrina', 'PO Box 78773');
insert into restoraunts (name, location) values ('Edin', 'Suite 38');
insert into restoraunts (name, location) values ('Marsh', '19th Floor');
insert into restoraunts (name, location) values ('Kerri', 'Room 699');
insert into restoraunts (name, location) values ('Adelice', 'Suite 33');
insert into restoraunts (name, location) values ('Idell', 'PO Box 25778');
insert into restoraunts (name, location) values ('Myrle', 'PO Box 30627');
insert into restoraunts (name, location) values ('Suzy', 'Room 1301');
insert into restoraunts (name, location) values ('Ailsun', '16th Floor');
insert into restoraunts (name, location) values ('Hubert', 'PO Box 68579');
insert into restoraunts (name, location) values ('Andi', 'Room 469');
insert into restoraunts (name, location) values ('Shani', 'Apt 56');
insert into restoraunts (name, location) values ('Natividad', 'PO Box 95505');
insert into restoraunts (name, location) values ('Rhys', '15th Floor');
insert into restoraunts (name, location) values ('Goober', '20th Floor');
insert into restoraunts (name, location) values ('Carlotta', 'Apt 1866');
insert into restoraunts (name, location) values ('Jeffrey', 'Suite 52');
insert into restoraunts (name, location) values ('Keith', 'PO Box 74514');
insert into restoraunts (name, location) values ('Perren', 'Room 777');
insert into restoraunts (name, location) values ('Burnaby', 'Room 1329');
insert into restoraunts (name, location) values ('Ruthanne', 'PO Box 7973');
insert into restoraunts (name, location) values ('Florenza', '9th Floor');
insert into restoraunts (name, location) values ('Fields', 'PO Box 60897');
insert into restoraunts (name, location) values ('Andria', 'PO Box 65947');
insert into restoraunts (name, location) values ('Deloris', 'Apt 1088');
insert into restoraunts (name, location) values ('Sibyl', 'Suite 15');
insert into restoraunts (name, location) values ('Florinda', 'Room 273');
insert into restoraunts (name, location) values ('Kelcie', 'PO Box 31006');
insert into restoraunts (name, location) values ('Ingeberg', 'Apt 605');
insert into restoraunts (name, location) values ('Jemmie', 'PO Box 9343');
insert into restoraunts (name, location) values ('Rudolph', 'PO Box 17686');
insert into restoraunts (name, location) values ('Jaquenette', 'Apt 380');
insert into restoraunts (name, location) values ('Sophie', 'Room 697');
insert into restoraunts (name, location) values ('Portia', 'PO Box 21100');
insert into restoraunts (name, location) values ('Ardith', 'PO Box 82803');
insert into restoraunts (name, location) values ('Andreana', 'Suite 40');
insert into restoraunts (name, location) values ('Hasty', 'Apt 1918');
insert into restoraunts (name, location) values ('Lian', '13th Floor');
insert into restoraunts (name, location) values ('Archibold', 'Apt 169');
insert into restoraunts (name, location) values ('Salli', '15th Floor');
insert into restoraunts (name, location) values ('Benny', 'Suite 56');
insert into restoraunts (name, location) values ('Claude', '9th Floor');
insert into restoraunts (name, location) values ('Hunt', 'Apt 1249');
insert into restoraunts (name, location) values ('Robina', 'Apt 918');
insert into restoraunts (name, location) values ('Desmund', 'PO Box 415');
insert into restoraunts (name, location) values ('Abby', 'Suite 43');
insert into restoraunts (name, location) values ('Monika', 'Apt 1622');
insert into restoraunts (name, location) values ('Munmro', 'Apt 1860');
insert into restoraunts (name, location) values ('Dacey', 'Suite 20');
insert into restoraunts (name, location) values ('Gus', 'Suite 35');
insert into restoraunts (name, location) values ('Ashbey', 'Apt 139');
insert into restoraunts (name, location) values ('Urbain', '8th Floor');
insert into restoraunts (name, location) values ('Zolly', '2nd Floor');
insert into restoraunts (name, location) values ('Darrelle', 'Apt 668');
insert into restoraunts (name, location) values ('Alli', 'Suite 32');
insert into restoraunts (name, location) values ('Lucia', 'PO Box 44423');
insert into restoraunts (name, location) values ('Laurens', 'Room 1114');
insert into restoraunts (name, location) values ('Teddy', 'Apt 691');
insert into restoraunts (name, location) values ('Robb', '3rd Floor');
insert into restoraunts (name, location) values ('Emeline', 'Room 1210');
insert into restoraunts (name, location) values ('Lindy', 'PO Box 49639');
insert into restoraunts (name, location) values ('Nadine', 'Room 659');
insert into restoraunts (name, location) values ('Maritsa', '6th Floor');
insert into restoraunts (name, location) values ('Otis', 'PO Box 91816');
insert into restoraunts (name, location) values ('Haslett', '12th Floor');
insert into restoraunts (name, location) values ('Ric', 'Suite 60');
insert into restoraunts (name, location) values ('Emmaline', 'Suite 76');
insert into restoraunts (name, location) values ('Ripley', 'Room 484');
insert into restoraunts (name, location) values ('Irvine', '1st Floor');
insert into restoraunts (name, location) values ('Meta', 'Suite 30');
insert into restoraunts (name, location) values ('Gabie', 'Apt 1227');
insert into restoraunts (name, location) values ('Emelda', 'Room 139');
insert into restoraunts (name, location) values ('Wiatt', 'Room 301');
insert into restoraunts (name, location) values ('Lorenzo', 'Room 1839');
insert into restoraunts (name, location) values ('Hunter', '4th Floor');
insert into restoraunts (name, location) values ('Parke', 'Room 301');
insert into restoraunts (name, location) values ('Germain', '2nd Floor');
insert into restoraunts (name, location) values ('Ikey', '11th Floor');
insert into restoraunts (name, location) values ('Flossy', 'Apt 1811');
insert into restoraunts (name, location) values ('Westley', 'Apt 456');
insert into restoraunts (name, location) values ('Christiano', 'Room 1495');
insert into restoraunts (name, location) values ('Marylynne', 'PO Box 32402');
insert into restoraunts (name, location) values ('Georgianne', '19th Floor');
insert into restoraunts (name, location) values ('Trista', 'Suite 70');
insert into restoraunts (name, location) values ('Blondell', 'Suite 42');
insert into restoraunts (name, location) values ('Butch', 'Suite 96');
insert into restoraunts (name, location) values ('Dyane', 'PO Box 4125');
insert into restoraunts (name, location) values ('Melinde', 'Room 1539');
insert into restoraunts (name, location) values ('Micky', 'PO Box 7817');
insert into restoraunts (name, location) values ('Maura', 'Apt 374');
insert into restoraunts (name, location) values ('Gram', 'PO Box 65648');
insert into restoraunts (name, location) values ('Dona', 'Apt 452');
insert into restoraunts (name, location) values ('Anissa', 'Apt 1771');
insert into restoraunts (name, location) values ('Buckie', 'PO Box 59927');
insert into restoraunts (name, location) values ('Janean', 'Apt 808');
insert into restoraunts (name, location) values ('Janis', '8th Floor');
insert into restoraunts (name, location) values ('Vanda', 'Room 428');
insert into restoraunts (name, location) values ('Candy', 'PO Box 1342');
insert into restoraunts (name, location) values ('Wang', '11th Floor');
insert into restoraunts (name, location) values ('Mikey', 'PO Box 4330');
insert into restoraunts (name, location) values ('Farand', 'Room 1047');
insert into restoraunts (name, location) values ('Heddie', 'Room 1380');
insert into restoraunts (name, location) values ('Walsh', '3rd Floor');
insert into restoraunts (name, location) values ('Basile', 'Room 321');
insert into restoraunts (name, location) values ('Loise', '7th Floor');
insert into restoraunts (name, location) values ('Ryon', 'PO Box 94384');
insert into restoraunts (name, location) values ('Peyton', 'PO Box 35084');
insert into restoraunts (name, location) values ('Pooh', 'Suite 23');
insert into restoraunts (name, location) values ('Freida', 'PO Box 99833');
insert into restoraunts (name, location) values ('Elvera', '6th Floor');
insert into restoraunts (name, location) values ('Haley', 'Room 1860');
insert into restoraunts (name, location) values ('Venita', 'Suite 54');
insert into restoraunts (name, location) values ('Andriette', 'Room 606');
insert into restoraunts (name, location) values ('Erasmus', 'PO Box 77685');
insert into restoraunts (name, location) values ('Claude', 'Suite 63');
insert into restoraunts (name, location) values ('Celestina', '10th Floor');
insert into restoraunts (name, location) values ('Artemis', 'Room 822');
insert into restoraunts (name, location) values ('Lilla', 'Room 550');
insert into restoraunts (name, location) values ('Jerald', '7th Floor');
insert into restoraunts (name, location) values ('Jerrie', '20th Floor');
insert into restoraunts (name, location) values ('Jervis', '17th Floor');
insert into restoraunts (name, location) values ('Sax', 'Suite 77');
insert into restoraunts (name, location) values ('Dulcea', 'Suite 83');
insert into restoraunts (name, location) values ('Jasun', 'Apt 466');
insert into restoraunts (name, location) values ('Gregorio', 'Room 1626');
insert into restoraunts (name, location) values ('Travis', 'PO Box 86277');
insert into restoraunts (name, location) values ('Ainsley', 'Suite 78');
insert into restoraunts (name, location) values ('Atalanta', 'PO Box 69996');
insert into restoraunts (name, location) values ('Les', 'PO Box 44577');
insert into restoraunts (name, location) values ('Lindsy', 'Room 1682');
insert into restoraunts (name, location) values ('Mickie', 'Apt 1131');
insert into restoraunts (name, location) values ('Bunni', 'Apt 45');
insert into restoraunts (name, location) values ('Thorsten', '18th Floor');
insert into restoraunts (name, location) values ('Grayce', '9th Floor');
insert into restoraunts (name, location) values ('Gian', '3rd Floor');
insert into restoraunts (name, location) values ('Caresse', '13th Floor');
insert into restoraunts (name, location) values ('Stacy', 'Room 739');
insert into restoraunts (name, location) values ('Hedvige', 'PO Box 71015');
insert into restoraunts (name, location) values ('Golda', 'Apt 814');
insert into restoraunts (name, location) values ('Kurtis', 'Apt 1094');
insert into restoraunts (name, location) values ('Venus', 'Suite 85');
insert into restoraunts (name, location) values ('Paulie', 'Apt 171');
insert into restoraunts (name, location) values ('Ase', '14th Floor');
insert into restoraunts (name, location) values ('Renaldo', 'PO Box 88395');
insert into restoraunts (name, location) values ('Larissa', 'PO Box 60300');
insert into restoraunts (name, location) values ('Garrott', 'Apt 1365');
insert into restoraunts (name, location) values ('Anjanette', 'Suite 95');
insert into restoraunts (name, location) values ('Irving', '8th Floor');
insert into restoraunts (name, location) values ('Aubrette', 'Room 737');
insert into restoraunts (name, location) values ('Elissa', '5th Floor');
insert into restoraunts (name, location) values ('Chrysler', 'PO Box 80734');
insert into restoraunts (name, location) values ('Wallas', 'Room 1757');
insert into restoraunts (name, location) values ('Morse', 'Apt 33');
insert into restoraunts (name, location) values ('Daren', 'Apt 475');
insert into restoraunts (name, location) values ('Jae', 'Room 110');
insert into restoraunts (name, location) values ('Arch', '10th Floor');
insert into restoraunts (name, location) values ('Giustino', 'Room 369');
insert into restoraunts (name, location) values ('Glenden', 'PO Box 74422');
insert into restoraunts (name, location) values ('Ree', '7th Floor');
insert into restoraunts (name, location) values ('Kessiah', 'Room 1661');
insert into restoraunts (name, location) values ('Quintana', 'Apt 740');
insert into restoraunts (name, location) values ('Kailey', 'Suite 53');
insert into restoraunts (name, location) values ('Cobby', 'Room 1757');
insert into restoraunts (name, location) values ('Molly', 'Apt 166');
insert into restoraunts (name, location) values ('Sibyl', '11th Floor');
insert into restoraunts (name, location) values ('Harwilll', 'Room 300');
insert into restoraunts (name, location) values ('Gonzales', 'Suite 40');
insert into restoraunts (name, location) values ('Franciska', 'Suite 68');
insert into restoraunts (name, location) values ('Trudy', 'Room 383');
insert into restoraunts (name, location) values ('Auroora', '16th Floor');
insert into restoraunts (name, location) values ('Lonni', 'Suite 25');
insert into restoraunts (name, location) values ('Orson', 'Suite 96');
insert into restoraunts (name, location) values ('Bride', 'Room 875');
insert into restoraunts (name, location) values ('Franciskus', 'Room 861');
insert into restoraunts (name, location) values ('Whitaker', 'Apt 888');
insert into restoraunts (name, location) values ('Archibold', 'Apt 865');
insert into restoraunts (name, location) values ('Nan', 'PO Box 63178');
insert into restoraunts (name, location) values ('Amory', '13th Floor');
insert into restoraunts (name, location) values ('Brittni', 'PO Box 8283');
insert into restoraunts (name, location) values ('Edgar', 'Apt 1693');
insert into restoraunts (name, location) values ('Chantal', 'Suite 81');
insert into restoraunts (name, location) values ('Colver', 'Apt 1730');
insert into restoraunts (name, location) values ('Gregg', 'Suite 83');
insert into restoraunts (name, location) values ('Kalvin', 'PO Box 3315');
insert into restoraunts (name, location) values ('Arlina', 'PO Box 11485');
insert into restoraunts (name, location) values ('Anna-diana', 'Suite 22');
insert into restoraunts (name, location) values ('Annie', 'Suite 8');
insert into restoraunts (name, location) values ('Nada', 'Suite 62');
insert into restoraunts (name, location) values ('Roderic', 'Suite 82');
insert into restoraunts (name, location) values ('Weylin', 'Suite 65');
insert into restoraunts (name, location) values ('Dominica', 'PO Box 92349');
insert into restoraunts (name, location) values ('Renault', '19th Floor');
insert into restoraunts (name, location) values ('Erich', 'Suite 20');
insert into restoraunts (name, location) values ('Sapphire', '13th Floor');
insert into restoraunts (name, location) values ('Korella', 'Suite 54');
insert into restoraunts (name, location) values ('Theodosia', 'Room 1556');
insert into restoraunts (name, location) values ('Bobbi', 'PO Box 21763');
insert into restoraunts (name, location) values ('Pattie', 'PO Box 33187');
insert into restoraunts (name, location) values ('Juliane', 'Room 1605');
insert into restoraunts (name, location) values ('Maryellen', 'Suite 32');
insert into restoraunts (name, location) values ('Ronalda', 'Apt 567');
insert into restoraunts (name, location) values ('Maitilde', 'PO Box 38838');
insert into restoraunts (name, location) values ('Geralda', 'Apt 715');
insert into restoraunts (name, location) values ('Berty', 'PO Box 20844');
insert into restoraunts (name, location) values ('Allyson', 'Suite 15');
insert into restoraunts (name, location) values ('Jorgan', 'Suite 20');
insert into restoraunts (name, location) values ('Fairlie', 'Suite 85');
insert into restoraunts (name, location) values ('Rabi', '3rd Floor');
insert into restoraunts (name, location) values ('Marigold', 'PO Box 99116');
insert into restoraunts (name, location) values ('Bell', '9th Floor');
insert into restoraunts (name, location) values ('Gardner', 'Apt 1872');
insert into restoraunts (name, location) values ('Nancy', 'Apt 1527');
insert into restoraunts (name, location) values ('Delilah', 'Suite 89');
insert into restoraunts (name, location) values ('Nehemiah', '18th Floor');
insert into restoraunts (name, location) values ('Nadiya', '6th Floor');
insert into restoraunts (name, location) values ('Ranique', '3rd Floor');
insert into restoraunts (name, location) values ('Alia', 'Apt 442');
insert into restoraunts (name, location) values ('Silvia', 'Room 1781');
insert into restoraunts (name, location) values ('Ammamaria', 'Suite 71');
insert into restoraunts (name, location) values ('Wyn', 'Suite 23');
insert into restoraunts (name, location) values ('Tobin', 'PO Box 46179');
insert into restoraunts (name, location) values ('Dallis', 'Apt 1266');
insert into restoraunts (name, location) values ('Simon', 'Room 32');
insert into restoraunts (name, location) values ('Janean', '19th Floor');
insert into restoraunts (name, location) values ('Woodrow', 'Apt 588');
insert into restoraunts (name, location) values ('Carver', 'Apt 1759');
insert into restoraunts (name, location) values ('Darrelle', 'Room 131');
insert into restoraunts (name, location) values ('Rozanne', 'Room 416');
insert into restoraunts (name, location) values ('Retha', 'Apt 1038');
insert into restoraunts (name, location) values ('Doti', 'Suite 86');
insert into restoraunts (name, location) values ('Nona', 'PO Box 5733');
insert into restoraunts (name, location) values ('Lilyan', 'Apt 866');
insert into restoraunts (name, location) values ('Delmar', 'PO Box 37751');
insert into restoraunts (name, location) values ('Alys', 'Room 477');
insert into restoraunts (name, location) values ('Arly', 'PO Box 71217');
insert into restoraunts (name, location) values ('Lorain', 'Suite 97');
insert into restoraunts (name, location) values ('Katie', '18th Floor');
insert into restoraunts (name, location) values ('Nelly', 'Suite 66');
insert into restoraunts (name, location) values ('Vilma', 'Room 1893');
insert into restoraunts (name, location) values ('Mycah', 'Suite 31');
insert into restoraunts (name, location) values ('Reece', 'PO Box 61846');
insert into restoraunts (name, location) values ('Natalie', 'Suite 46');
insert into restoraunts (name, location) values ('Aggie', '10th Floor');
insert into restoraunts (name, location) values ('Pauly', 'Suite 92');
insert into restoraunts (name, location) values ('Kiah', 'Room 481');
insert into restoraunts (name, location) values ('Maddie', 'PO Box 80741');
insert into restoraunts (name, location) values ('Darnell', '8th Floor');
insert into restoraunts (name, location) values ('Alonso', 'Room 1580');
insert into restoraunts (name, location) values ('Tull', '4th Floor');
insert into restoraunts (name, location) values ('Neel', 'Room 1790');
insert into restoraunts (name, location) values ('Terri', 'PO Box 93594');
insert into restoraunts (name, location) values ('Robb', 'PO Box 21877');
insert into restoraunts (name, location) values ('Waylin', '9th Floor');
insert into restoraunts (name, location) values ('Tiena', 'Apt 653');
insert into restoraunts (name, location) values ('Reider', 'Suite 18');
insert into restoraunts (name, location) values ('Pincas', '17th Floor');
insert into restoraunts (name, location) values ('Josias', '16th Floor');
insert into restoraunts (name, location) values ('Lynn', 'Suite 16');
insert into restoraunts (name, location) values ('Ingar', '17th Floor');
insert into restoraunts (name, location) values ('Yalonda', 'PO Box 42533');
insert into restoraunts (name, location) values ('Rand', 'Room 1215');
insert into restoraunts (name, location) values ('Delano', 'Apt 1669');
insert into restoraunts (name, location) values ('Roshelle', 'Apt 326');
insert into restoraunts (name, location) values ('Jillene', '17th Floor');
insert into restoraunts (name, location) values ('Dimitry', '15th Floor');
insert into restoraunts (name, location) values ('Hale', 'Room 3');
insert into restoraunts (name, location) values ('Denys', 'PO Box 41948');
insert into restoraunts (name, location) values ('Ashlan', '5th Floor');
insert into restoraunts (name, location) values ('Ephraim', 'Suite 46');
insert into restoraunts (name, location) values ('Cos', 'PO Box 53000');
insert into restoraunts (name, location) values ('Ambros', 'Room 1952');
insert into restoraunts (name, location) values ('Padraic', '1st Floor');
insert into restoraunts (name, location) values ('Cheslie', 'Suite 20');
insert into restoraunts (name, location) values ('Andee', '19th Floor');
insert into restoraunts (name, location) values ('Marcellus', 'Suite 46');
insert into restoraunts (name, location) values ('Rabi', 'PO Box 98615');
insert into restoraunts (name, location) values ('Wren', 'Suite 46');
insert into restoraunts (name, location) values ('Ad', '5th Floor');
insert into restoraunts (name, location) values ('Muriel', 'Apt 405');
